[FEAT] 네트워크 관련 기본세팅
Nexters/www-iOS pull request #25
Opened 2023-02-10 06:44 UTC by kokojong

## Background

- closes #8 

## Description

 

1. Moya를 활용해서 RxMoyaProvider 를 만들었어요
2. Clean Architecture의 예시를 보며 (따라서) 파일 구조를 나눠봤어요
3. 처음에는 VM에서 API call을 직접 했지만 클린아키텍쳐 형식으로 적용해봤어요

## Extra Notes 

- 클린아키텍쳐를 공부하면서 한거라 의견은 언제나 '환영' (제대로 한게 맞는지 모르겠으..)
- SceneDelegate에서 sampleVC를 선언하는 과정에서 어려움이 있었는데 이렇게 하는거 맞는쥐...

## 참고 사항

- 내 머릿속
- https://ios-development.tistory.com/797
- https://github.com/pcsoyeon/Network

- https://github.com/kudoleh/iOS-Clean-Architecture-MVVM
- https://github.com/kwontaewan/iOS-Clean-Architecture-MVVM-RxSwift
- https://github.com/Youngminah/ServiceLevelProject (같이 부트캠프 한 친구 플젝! 기능등을 알고있어서 이해할때 도움이 되어따)

2023-02-11 06:02 UTC, chaneeii requested changes
에러매핑이랑 로거 나중에 달면 좋을 것 같고
네트워크 모듈은 나도 쓰면서 같이 개선할게! 
뷰에 띄우는거까지 했을 줄을 몰랐는데 클린아키텍처에 초안짜느랴 고생많았어 
![image](https://user-images.githubusercontent.com/63157395/218243229-ca021f71-dd5b-42ee-bc7e-f0a1a5f1bafb.png)


그리고 백엔드 부분에 변경사항들이 있어서 이부분 내일 같이 반영하면 좋을듯
1. baseurl 변경 (https 적용)
2. api 세부 사항 변경

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Sources/Data/Network/UserAPI.swift
> +
p2)
아직 아무것도 없어서 괜찮지만 이게 보안상 노출되는게 좋지는 않아서
이건 따로 Constants 나 따로 빼서 관리하는거 어때요?

해당파일 .gitignore 처리하고 저희끼리 공유하죠..!

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Support/Info.plist
> +	</dict>
p5)
// MARK: - 이부분은 이거 맞춰서 바꾸기
<img width="435" alt="스크린샷 2023-02-10 오후 9 04 37" src="https://user-images.githubusercontent.com/63157395/218088284-813b2821-6f24-4cfc-9710-5ad2b9e1a350.png">

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Sources/Domain/UseCases/User/JoinUserUseCase.swift
> +}
p1)
이거 JoinUserUseCaseUseCase 로 교체좀..!
샘플에 내가 복붙 잘못해서 틀린거야 ㅎㅎ

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Sources/Presentation/Main/SampleViewModel.swift
> +    }
💬
이건 테스트용이랑 괜찮은데 클린아키텍처에서 DTO는 데이터 레이어에만 있는게 좋아요 👍
이런건 안티 패턴이라 도메인레이어에서 도메인 객체로 바꿔주세용

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Support/Info.plist
> +	</dict>
백엔드 협의 결과 금일 (2월 11일 토요일) 배포 예정이라구 하네요! 
@tjdcks12 @emost22 맞죠,...?

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Sources/Presentation/Main/SampleViewModel.swift
> +    private let joinUserUseCase: JoinUserUseCaseProtocol
p1)
JoinUserUseCaseProtocol 이 아닌 구현체인 JoinUserUseCase 이 와야합니다~!

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Sources/Presentation/Main/SampleViewController.swift
> +        }.disposed(by: bag)
💬
오호! 이렇게 연결해서 사용하는 군요

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Sources/Data/DTO/User/LoginRequestDTO.swift
> +}
p1)
2월 11일자 기준으로 백엔드 API 에 큰 변화가 생길 예정이라 (오늘안에 변경사항 적용된다구함) 내일 다시 백엔드 변경사항 전반적으로 수정해야할듯!

(필드 네이밍, DTO 이름 등이 바뀐데요

2023-02-11 06:02 UTC, chaneeii commented on Projects/App/Sources/Data/Repositories/UserDAO.swift
> +            .map(LoginResponseDTO.self)
p1)
매핑 방식은 다양한데 여기서 도메인 객체로 매핑해야합니당~

2023-02-11 06:09 UTC, chaneeii commented
Merge 가 안될때는 Rebase 쓰면되는데 크라켄에서는 아래처럼 하면 엄청 간단하게 할 수 있어!
충돌난것만 해결해주면 될듯!
<img width="541" alt="스크린샷 2023-02-11 오후 2 35 22" src="https://user-images.githubusercontent.com/63157395/218243435-57d867ed-e3dc-4612-9e05-ce8277ea8c13.png">

2023-02-11 10:35 UTC, kokojong commented on Projects/App/Sources/Data/Network/UserAPI.swift
> +
안그래도 일단은 처음에 만드는거라 이렇게 하드코딩으로 되어이따..!
const로 관리하는거 좋아

2023-02-11 10:38 UTC, kokojong commented on Projects/App/Sources/Presentation/Main/SampleViewModel.swift
> +    }
오케이! 그러면 예시에 있는 toDomain 같은 거로 다시 매핑하면 되려나?
저기서 entity를 뭐로 해야할지 모르겠어서 일단은 DTO를 가져다가 썼는 result만 entity로 쓰면 될까??

2023-02-11 10:38 UTC, kokojong commented on Projects/App/Sources/Presentation/Main/SampleViewController.swift
> +        }.disposed(by: bag)
웅 결국 bindRx 에서는 output에 대한 내용만 받아오는식으로..!

2023-02-11 10:38 UTC, kokojong commented on Projects/App/Sources/Data/DTO/User/LoginRequestDTO.swift
> +}
확인했으요~

2023-02-11 10:39 UTC, kokojong commented on Projects/App/Sources/Data/Repositories/UserDAO.swift
> +            .map(LoginResponseDTO.self)
엔티티 정해지고 api 수정되면 toDomain 으로 변환하는거 할게!

2023-02-11 11:12 UTC, kokojong commented
conflict는 일단 해결..!
깃크라켄 리베이스 저렇게 할수있는거 대박이네.

2023-02-11 11:49 UTC, kokojong commented on Projects/App/Sources/Domain/UseCases/User/JoinUserUseCase.swift
> +}
JoinUserUseCase 맞지..?
c9dc010b2c2baa27e44d6bde394aec51cb517ca8 에 반영

2023-02-11 11:50 UTC, kokojong commented on Projects/App/Sources/Presentation/Main/SampleViewModel.swift
> +    private let joinUserUseCase: JoinUserUseCaseProtocol
아 그러네 프로토콜이 아니네!
6999463e47048718b198e8066e3db27feaf54fd0 에 반영

2023-02-11 12:39 UTC, emost22 commented on Projects/App/Support/Info.plist
> +	</dict>
PR 밀린거 처리돼서 배포는 끝! 요청 보내보셔도 됩니다~
Swagger는 http에 요청이 가도록 되어있어서 수정하고 알려드릴게요!

2023-02-12 06:03 UTC, kokojong commented on Projects/App/Sources/Data/Network/UserAPI.swift
> +
fbe74daf816c8c0f9dce111726a40b5a3cd9376e 에 적용!

2023-02-12 06:06 UTC, kokojong commented on Projects/App/Sources/Data/DTO/User/LoginRequestDTO.swift
> +}
@chaneeii user/join 부분에서는 바뀐게 없어서 일단 둘게! toDomian 부분만 작업해 둘게!

2023-02-12 06:23 UTC, kokojong commented on Projects/App/Support/Info.plist
> +	</dict>
3866df595ffd94e55a973031254a748cbe5e3bce 에서 plist 수정!

2023-02-12 06:41 UTC, kokojong commented on Projects/App/Sources/Data/Repositories/UserDAO.swift
> +            .map(LoginResponseDTO.self)
10ca7556d96119cd0072db18743bc917a6dfb6f4 에 적용!

2023-02-12 06:42 UTC, kokojong commented on Projects/App/Sources/Data/DTO/User/LoginRequestDTO.swift
> +}
10ca7556d96119cd0072db18743bc917a6dfb6f4 에 적용!

2023-02-12 06:42 UTC, kokojong commented on Projects/App/Sources/Presentation/Main/SampleViewModel.swift
> +    }
@chaneeii CommonResponse 라는걸 만들어서 code, message, result 이렇게 만들어 봤어!
10ca7556d96119cd0072db18743bc917a6dfb6f4

2023-02-12 08:58 UTC, chaneeii commented on Projects/App/Sources/Presentation/Main/SampleViewModel.swift
> +    }
CommonResponse 좋네요! 
안그래도 있으면 좋을 것 같았는데 👍👍👍👍

2023-02-12 08:59 UTC, chaneeii commented
👏👏👏 고생했습니당

2023-02-12 09:00 UTC, chaneeii approved these changes

2023-02-13 02:07 UTC, merged